### PR TITLE
adding new contentTypes related to TVB pipeline

### PR DESCRIPTION
**Pull request by lzehl**
relevant for https://search.kg.ebrains.eu/instances/4edef2ff-e653-40a5-a222-0a5759fdaaaf
+ json (specific for old MINDS, as far as formerly specified)
+ tsv (specific for TVB)

### CODE REVIEW

**Comment by lzehl** [comment]
@jagru20 / @apdavison : I do not know who of you has more time at the moment ;) (one of you for the review is enough I guess)

**Review by apdavison — COMMENTED** [review]
I think it would be better to spell out tvb in full, and also to specify what kind of data are being stored, because I presume TVB works with multiple different formats, i.e. `application/vnd.thevirtualbrain.connectivity+tsv` (where "connectivity" would be replaced with whatever is actually in the files)

**Comment by lzehl** [comment]
@apdavison yes you are right. I'll change it

**Comment by lzehl** [comment]
done :)

**Review by apdavison — APPROVED** [review]

**Pull request merged**
