### PR TITLE
Create controlledTerm.schema.json

### PR DESCRIPTION
**Pull request by UlrikeS91**
based on #78

### CODE REVIEW

**Comment by skoehnen** [comment]
Hi @UlrikeS91 I rebased your pull request so it uses the new CI script.

**Review by skoehnen — APPROVED** [review]
Looks good to me.

**Comment by lzehl** [comment]
@skoehnen something is wrong with this merged branch. The check failed... I can't see though why. Can you?

**Comment by skoehnen** [comment]
> @skoehnen something is wrong with this merged branch. The check failed... I can't see though why. Can you?

The problem is with datasetversion 
`../openMINDS/v3.0/products/datasetversion.schema.json failed validation`

@xgui3783 found an error in the validation script that let errors slip through.
I fixed the error in the script and the validation errors that made it into the repository, but the last one, #91 is still under review.
As soon as that is merged we are green across the board.

**Comment by skoehnen** [comment]
@lzehl you can check the output of the script if you click on details of the merge.

**Pull request merged**
