### PR TITLE
updating file schemas

### PR DESCRIPTION
**Pull request by lzehl**
related to #190 

Additionally:
@olinux split repo from bundle here, because one file can belong to multiple bundles but only one repository.

### CODE REVIEW

**Comment by lzehl** [comment]
@olinux : I've also need to update SANDS considering the fileInstance->file change (@UlrikeS91 you could double check as well here)

**Comment by lzehl** [comment]
this PR is also related to https://github.com/HumanBrainProject/openMINDS_core/issues/190

**Comment by apdavison** [comment]
> one file can belong to multiple bundles but only one repository

can you explain this in more detail? Can the bundles be in different repositories?

If a file is copied from one repository to another, I would want to represent this as a single File object that is linked to both repositories. On that topic, are you in contact with anyone from T6.3? They are working on a data location service that I think should be based on File/FileBundle/FileRepository.

**Comment by lzehl** [comment]
@apdavison based on a discussion with @olinux we agreed that a file bundle is defined by the files it is grouping. Within the KG a single file can only belong to one repository because we wanted to be able to assign clear/distinct download locations (full paths) for each file. A file that is copied to another repository would therefore get another entry. The relation of such copies are currently not represented in openMINDS. The file can link to multiple file bundles. If all the files that point to the same bundle are part of the same repository it can be inferred that this bundle is also part of this repository. In principle we are not forbidding that a file bundle could hold files of different repositories, although we try to avoid it by creating most file/file bundle relations automatically within the same file repository.

I was not yet with anyone of T6.3 I think. Is this connected to DataLad by any chance? Then indirectly in contact already.

**Comment by apdavison** [comment]
The ability to link different copies of the same file is essential for provenance, and is probably also needed for the data location service. Perhaps we could add this issue to the agenda for when we meet to talk about openMINDS extensions?

**Comment by lzehl** [comment]
@apdavison yes! I agree we should definitely put it on the agenda list. I made a note. Thanks for bringing it up.

**Review by UlrikeS91 — APPROVED** [review]

**Pull request merged**
