### PR TITLE
Adding Setup schema to core

### PR DESCRIPTION
**Pull request by Peyman-N**
Some time researchers create their own devices by daisy changing existante devices. In an effort for capturing these instruments I suggest to add a `setup` and `setupVersion` schema. 

The `setup` schema have following properties:
`internalIdentifier`  The identifier used for this setup 
`location` The location that the setup is situated.   
`project`  The projects that have used this setup. 
`hasVersion`
`description`

The `setupVersion` schema have the following properties:
`versionIdentifier` 
`developer` All the developers participated in creating this setup
`isNewVersionOf` 
`hardwares` All the components of this setupVersion it can contain both other setup and hardware 
`description`

### CODE REVIEW

**Comment by lzehl** [comment]
@Peyman-N I'm not sure I will find the time soon to review this PR. I hope it can wait a bit?

**Comment by Peyman-N** [comment]
@lzehl No problem, actually this pull request would need more discussion so lets do it when you have time. On the same note, I would do some other pull request during the week, most of them are not urgent, so you can review them when you have time.

**Comment by jcolomb** [comment]
You may want to have a look at https://barbal.co/the-open-know-how-manifest-specification-version-1-0/
this is the work done by the open hardware community to get similar information in a computer readable way.

I will have a closer look in the coming weeks.

**Review by lzehl — COMMENTED** [review]
@Peyman-N thank you for this first PR. In combination with the review of other PRs (e.g., #270) we (@UlrikeS91 & @lzehl ) suggest the following changes:

1) Merge Setup and SetupVersion into one schema (remove all version properties). Reason: Small changes can already constitute a different setup, and gradually increasing number of changes make it hard to distinguish when it is still a version or a new setup. Therefore its easier to just consider any change as a new setup.

2) We are unaware of common usage of an internal identifier for a setup. Would it not be more fitting to just ask for a name of the setup?

3) It would be good to introduce a setup type (linked in as new controlledTerm). (e.g., "acquisition system" or something a bit more specific)

4) property "project" needs to be removed. This linkage need to be made from the research products or project to the setup.

5) property "hardwares" should be renamed to "components" with linkedTypes Device and SoftwareVersion.

6) properties "description", "developer", "location" are fine. however, the instructions should provide a bit more information what is meant / expected for each property.

7) required properties in changed schema: "name", "components", "description"

**Review by UlrikeS91 — CHANGES_REQUESTED** [review]
worked on suggestion together, see our proposal

**Comment by UlrikeS91** [comment]
Conclusion from offline meeting with @apdavison @Peyman-N and @lzehl 

> 1. Merge Setup and SetupVersion into one schema (remove all version properties). Reason: Small changes can already constitute a different setup, and gradually increasing number of changes make it hard to distinguish when it is still a version or a new setup. Therefore its easier to just consider any change as a new setup.
> 2. We are unaware of common usage of an internal identifier for a setup. Would it not be more fitting to just ask for a name of the setup?
> 3. It would be good to introduce a setup type (linked in as new controlledTerm). (e.g., "acquisition system" or something a bit more specific)
> 4. property "project" needs to be removed. This linkage need to be made from the research products or project to the setup.
> 5. property "hardwares" should be renamed to "components" with linkedTypes Device and SoftwareVersion.
> 6. properties "description", "developer", "location" are fine. however, the instructions should provide a bit more information what is meant / expected for each property.
> 7. required properties in changed schema: "name", "components", "description"

Point 3 should be made an array, because it may have several functions. 
Other systems: "stimulation system", "computing system" (e.g. SpiNNaker setup)

Point 5 need very explicit instructions: Every setup has to have one hardware device. 

Rest is fine.

**Review by UlrikeS91 — APPROVED** [review]

**Review by lzehl — APPROVED** [review]

**Review by apdavison — APPROVED** [review]

**Pull request merged**
