### PR TITLE
Update datasetversion.schema.json

### PR DESCRIPTION
**Pull request by UlrikeS91**
based on #74

### CODE REVIEW

**Review by skoehnen — APPROVED** [review]
Looks good to me.

**Comment by lzehl** [comment]
@UlrikeS91 Next PR for this one: the schema filename should be "datasetVersion.schema.json" and some of the implementation needs to be adopted to the discussion/comments in #74.

**Comment by UlrikeS91** [comment]
I will update it now based on the comments in #74 and I will already change `ethicsApproval` to `ethicsAssessment` (with `controlledTerm`as object and count = 1). I cannot see a reason Will/Ida would have anything against this, and even if they do, it's easy to change it again ;)

**Comment by lzehl** [comment]
I agree! Go ahead!

**Pull request merged**
