### PR TITLE
deleting a duplicate

### PR DESCRIPTION
**Pull request by lzehl**
This is the same as `moleculardevices.axon.jsonld`

### CODE REVIEW

**Comment by lzehl** [comment]
@apdavison can this be merged? @jagru20 does this affect any software registered in the openMINDS based KG?

**Comment by apdavison** [comment]
ok with me

**Comment by jagru20** [comment]
These instances use it as input format:

- [ ] 0b0ea86d-38cc-4dd6-8ebf-148761fbdd47
- [ ] 110ec81c-afb7-40da-96c9-4edc69b8b9c5
- [ ] 21a7e803-6da6-4cde-b726-5a824efcafbf
- [ ] 49864d1b-df9e-44c9-93c0-5d23a1f6017e
- [ ] 715dbd5e-7b1e-49d8-9c83-2538e60f140e
- [ ] a9336caf-0df3-4a5e-81fa-5e071c3e2d24
- [ ] bb03793f-c014-43e7-8c06-844aba5a8bac
- [ ] be739df8-242f-4d00-b935-c30ca1dff868
- [ ] ca91ee5d-398f-49eb-9132-034847965814

and these as output:

- [ ] 110ec81c-afb7-40da-96c9-4edc69b8b9c5
- [ ] ca91ee5d-398f-49eb-9132-034847965814

I am not sure, which ones rely on one or the other jsonld.

**Comment by lzehl** [comment]
@jagru20 thanks for this summary. I'm updating the KG first then and merge the PR afterwards.

**Comment by lzehl** [comment]
I've realized that both instances have actually the same `@id` so I'm just gonna merge this PR now. The Software instances in the EBRAINS KG should not have any changes (since the other instance with the same `@id` still exists).

**Pull request merged**
