### PR TITLE
Clean up: subject

### PR DESCRIPTION
**Pull request by UlrikeS91**
MINOR changes:
- improved instructions

MAJOR changes:
none

SPECIAL ATTENTION:
none

### CODE REVIEW

**Review by lzehl — COMMENTED** [review]
@apdavison please double check ("... of which ... is part of." OR "... of which ... is a part" ??)

**Review by Peyman-N — CHANGES_REQUESTED** [review]
I think we using "... of which ... is part of." is not correct as of which already implies it and having it again is not necessary. I suggest one of the following possibilities: 
"Add all subject groups this subject belongs to."
"Add all subject groups of which this subject is a part."
"Add all subject groups of which this subject is a member."
"Add all subject groups this subject is part of."

**Review by lzehl — APPROVED** [review]

**Comment by lzehl** [comment]
@Peyman-N I took you last suggestion. feel free to merge if you approve now.

**Comment by lzehl** [comment]
@Peyman-N or @apdavison or @aeidi89 feel free to merge if you approve as well now

**Review by Peyman-N — APPROVED** [review]

**Pull request closed without merging**
