### PR TITLE
Add/modify content types relating to NEST

### PR DESCRIPTION
**Pull request by apdavison**

### CODE REVIEW

**Comment by lzehl** [comment]
@apdavison do you understand why all checks fail for this PR? I can't see an error in your code.Is there a bug in the pipeline?

**Comment by apdavison** [comment]
The error message was 
```

./generator/generator/OpenMINDS_Base.py:5:8: E999 SyntaxError: unexpected EOF while parsing

```

**Comment by lzehl** [comment]
@skoehnen FYI (could you have a look at the OpenMINDS_Base.py, please?)

**Comment by skoehnen** [comment]
Was an old version of the file, I removed it for now.
Checks are now running.

**Review by lzehl — APPROVED** [review]

**Pull request merged**
